# Generated by Django 4.1 on 2022-08-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_alter_category_updated_at"),
        ("word", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="type",
            field=models.CharField(
                choices=[
                    ("noun", "NOUN"),
                    ("pronoun", "PRONOUN"),
                    ("verb", "VERB"),
                    ("adjective", "ADJECTIVE"),
                    ("adverb", "ADVERB"),
                    ("preposition", "PREPOSITION"),
                    ("conjunction", "CONJUNCTION"),
                    ("interjection", "INTERJECTION"),
                ],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="word",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words",
                to="category.category",
            ),
        ),
    ]
